# Generated by Django 5.2 on 2025-05-02 02:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_patient_numero_cns_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorName',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientName',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='admitDate',
            new_name='admit_date',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='assignedDoctorName',
            new_name='assigned_doctor_name',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='OtherCharge',
            new_name='day_spent',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='daySpent',
            new_name='doctor_fee',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='doctorFee',
            new_name='medicine_cost',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='medicineCost',
            new_name='other_charge',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='patientName',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='roomCharge',
            new_name='room_charge',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='admitDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='admit_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Clinico Geral', 'Clinico Geral'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_cns',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='numero_cns',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/NurseProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Clinico Geral', 'Clinico Geral'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Clinico Geral', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
