# Generated by Django 5.2 on 2025-05-02 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_rename_doctorname_appointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
