# Generated by Django 5.2 on 2025-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_patientdischargedetails_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Clinico Geral', 'Clinico Geral'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergistas/Immunologistas', 'Allergistas/Immunologistas'), ('Anestesiologistas', 'Anestesiologistas'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='department',
            field=models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Clinico Geral', 'Clinico Geral'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergistas/Immunologistas', 'Allergistas/Immunologistas'), ('Anestesiologistas', 'Anestesiologistas'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Clinico Geral', max_length=50),
        ),
    ]
